---
stages:
  - package

before_script:
  - echo "Running on ${HOST_HOSTNAME:=$(hostname)}"

.job_template: &job_definition
  stage: package
  image: "0xacab.org:4567/leap/gitlab-buildpackage:build_${DIST}_${ARCH}"
  script:
    - "pwd; git describe"
    - build-build-package
    # Test the package with lintian
    - build-test-lintian
    - upload-package
    # sleep 1h to allow debugging of running container
    # - sleep 3600
  artifacts:
    expire_in: 1w
    paths:
      - '*_*.xz'
      - '*_*.dsc'
      - '*_amd64.changes'
      - '*.deb'
      - 'results/*'


package:amd64_jessie:
  variables:
    ARCH: "amd64"
    DIST: "jessie"
    REPONAMES: "platform"
    # Default is to fail on warnings, we disable it here
    # unless the lintian warnings are fixed (see #2)
    LINTIAN_OPTS: "-X filename-length"
  <<: *job_definition

# package:amd64_stretch:
#  variables:
#    ARCH: "amd64"
#    DIST: "stretch"
#    REPONAMES: "platform"
#    # Default is to fail on warnings, we disable it here
#    # unless the lintian warnings are fixed (see #2)
#    LINTIAN_OPTS: "-X filename-length"
#  <<: *job_definition
