---
stages:
  - package

before_script:
  - echo "Running on ${HOST_HOSTNAME:=$(hostname)}"

.job_template: &job_definition
  stage: package
  image: "0xacab.org:4567/leap/gitlab-buildpackage:build_${DIST}_${ARCH}"
  script:
    - "pwd; git describe"
    - build-build-package
    # Test the package with lintian
    - build-test-lintian
    - upload-package
    # sleep 1h to allow debugging of running container
    # - sleep 3600
  artifacts:
    expire_in: 1w
    paths:
      - '*_*.xz'
      - '*_*.dsc'
      - '*_amd64.changes'
      - '*.deb'
      - 'results/*'


package:amd64_jessie:
  variables:
    ARCH: "amd64"
    DIST: "jessie"
    REPONAMES: "platform,client"
    # Default is to fail on warnings, we disable it here
    # Standard-Version is higher than available for this release
    LINTIAN_OPTS: "--fail-on-warnings -X filename-length,standards-version"
  <<: *job_definition

package:amd64_stretch:
  variables:
    ARCH: "amd64"
    DIST: "stretch"
    REPONAMES: "platform,client"
    # Default is to fail on warnings, we disable it here
    # Standard-Version is higher than available for this release
    LINTIAN_OPTS: "--fail-on-warnings -X filename-length,standards-version"
  <<: *job_definition

package:amd64_buster:
  variables:
    ARCH: "amd64"
    DIST: "buster"
    REPONAMES: "client"
  <<: *job_definition


package:amd64_zesty:
  variables:
    ARCH: "amd64"
    DIST: "zesty"
    REPONAMES: "client"
    # Default is to fail on warnings, we disable it here
    # Standard-Version is higher than available for this release
    LINTIAN_OPTS: "--fail-on-warnings -X filename-length,standards-version"
  <<: *job_definition

package:amd64_artful:
  variables:
    ARCH: "amd64"
    DIST: "artful"
    REPONAMES: "client"
  <<: *job_definition
